"""Platform-specific paths and cross-process file locking for the workbench."""
from __future__ import annotations

import errno
import os
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, TextIO


ROOT = Path(os.environ.get("FUND_WORKBENCH_ROOT", Path(__file__).resolve().parent)).expanduser().resolve()


def venv_python(root: Path = ROOT) -> Path:
    """Return the Python interpreter inside this checkout's virtual environment."""
    if os.name == "nt":
        return root / ".venv" / "Scripts" / "python.exe"
    return root / ".venv" / "bin" / "python"


def venv_script(name: str, root: Path = ROOT) -> Path:
    """Return a console-script path generated by pip in the project venv."""
    scripts = root / ".venv" / ("Scripts" if os.name == "nt" else "bin")
    return scripts / (name + (".exe" if os.name == "nt" else ""))


@contextmanager
def file_lock(file: TextIO, *, shared: bool = False) -> Iterator[None]:
    """Lock one byte of an opened lock file across processes.

    Windows only provides the byte-range msvcrt lock used here, so reads are
    exclusive there too. The caller's in-process lock still serializes threads.
    """
    if os.name == "nt":
        import msvcrt

        descriptor = file.fileno()
        if os.fstat(descriptor).st_size == 0:
            file.seek(0)
            file.write("\0")
            file.flush()
        while True:
            try:
                file.seek(0)
                msvcrt.locking(descriptor, msvcrt.LK_LOCK, 1)
                break
            except OSError as error:
                retry_errors = {errno.EACCES, errno.EAGAIN, getattr(errno, "EDEADLK", errno.EACCES),
                                getattr(errno, "EDEADLOCK", errno.EACCES)}
                if error.errno not in retry_errors:
                    raise
                time.sleep(0.1)
        try:
            yield
        finally:
            file.seek(0)
            msvcrt.locking(descriptor, msvcrt.LK_UNLCK, 1)
        return

    import fcntl

    mode = fcntl.LOCK_SH if shared else fcntl.LOCK_EX
    fcntl.flock(file.fileno(), mode)
    try:
        yield
    finally:
        fcntl.flock(file.fileno(), fcntl.LOCK_UN)
