'use strict';

const indexes = [
  {id:'sse',name:'上证指数',category:'大盘',points:'3,428.61',change:'+0.36%',amount:'成交额 4,126 亿元',status:'交易中',values:[22,24,25,23,27,26,28,27,30,29,33,32,35],note:'大盘整体小幅上涨。',color:'up'},
  {id:'szse',name:'深证成指',category:'大盘',points:'10,842.37',change:'-0.42%',amount:'成交额 5,391 亿元',status:'交易中',values:[34,36,33,31,30,32,29,28,30,27,26,25,24],note:'深市主要指数回落。',color:'down'},
  {id:'hs300',name:'沪深300',category:'大盘',points:'3,997.21',change:'+0.18%',amount:'成交额 2,864 亿元',status:'交易中',values:[20,22,23,21,24,25,23,26,27,26,29,28,30],note:'大盘蓝筹相对平稳。',color:'up'},
  {id:'zz500',name:'中证500',category:'风格',points:'5,874.90',change:'-0.58%',amount:'成交额 1,781 亿元',status:'交易中',values:[34,35,32,31,33,29,30,28,26,27,25,23,22],note:'中盘风格承压。',color:'down'},
  {id:'chinext',name:'创业板指',category:'成长',points:'2,214.08',change:'-1.42%',amount:'成交额 1,523 亿元',status:'交易中',values:[39,37,38,34,31,33,29,27,28,24,22,23,18],note:'成长板块盘中回落，跌幅较大。',color:'down'},
  {id:'zz1000',name:'中证1000',category:'风格',points:'6,288.45',change:'-0.67%',amount:'成交额 1,968 亿元',status:'交易中',values:[35,33,34,32,29,30,27,26,28,24,23,22,20],note:'小盘风格弱于大盘。',color:'down'},
  {id:'dividend',name:'中证红利',category:'风格',points:'5,162.30',change:'+0.41%',amount:'成交额 623 亿元',status:'交易中',values:[21,22,23,23,25,24,25,27,26,28,29,29,31],note:'红利风格小幅走强。',color:'up'},
  {id:'bond',name:'中债综合',category:'债市',points:'125.73',change:'+0.03%',amount:'净价指数',status:'延迟行情',values:[20,20,21,21,22,22,23,23,24,24,25,25,26],note:'债市数据更新频率与股票指数不同。',color:'up'},
  {id:'gold',name:'上海金',category:'商品',points:'652.40',change:'+0.29%',amount:'参考价',status:'延迟行情',values:[22,23,22,25,24,27,25,29,28,30,31,30,33],note:'商品行情与 A 股交易时段不同。',color:'up'},
  {id:'sp500',name:'标普500',category:'海外',points:'5,721.68',change:'+0.12%',amount:'上一交易日收盘',status:'休市',values:[21,20,23,24,22,25,26,25,28,29,27,30,31],note:'展示上一交易日收盘，不与 A 股盘中涨跌直接比较。',color:'up'}
];
const funds = [
  {id:'f-chinext',name:'创业板 ETF 联接 C',kind:'指数基金',nav:'1.2468',navDate:'9 月 23 日',month:'-3.72%',index:'chinext',relation:'基金合同约定跟踪创业板指数；具体跟踪误差受费用、申赎和现金仓位影响。',event:'申购限额调整',eventId:'limit',large:true,estimate:'盘中估算 -1.18%',values:[34,35,32,33,30,29,31,27,25,26,23,21,19]},
  {id:'f-hs300',name:'沪深300 ETF 联接 A',kind:'指数基金',nav:'1.7821',navDate:'9 月 23 日',month:'+1.65%',index:'hs300',relation:'基金合同约定跟踪沪深300指数；今日指数变化不是基金正式净值或你的账户收益。',event:'',eventId:'',large:false,estimate:'盘中估算 +0.11%',values:[19,21,22,20,24,25,24,26,27,28,29,30,31]},
  {id:'f-balanced',name:'均衡成长混合 A',kind:'主动基金',nav:'2.1357',navDate:'9 月 23 日',month:'-0.84%',index:null,relation:'主动管理基金没有单一指数的直接跟踪关系；只能结合已披露持仓和正式净值解释。',event:'基金经理变更',eventId:'manager',large:false,estimate:'暂无可靠盘中估算',values:[26,28,25,27,30,29,31,30,28,29,27,27,26]},
  {id:'f-bond',name:'中短债基金 A',kind:'债券基金',nav:'1.1032',navDate:'9 月 23 日',month:'+0.32%',index:null,relation:'债券基金净值不能用 A 股指数涨跌推断。',event:'',eventId:'',large:false,estimate:'暂无盘中估算',values:[18,19,19,20,20,21,21,22,22,23,23,24,25]}
];
const events = [
  {id:'limit',title:'创业板 ETF 联接 C 申购限额调整',status:'需要处理',time:'9 月 24 日 11:20',fundIds:['f-chinext'],source:'基金临时公告（演示）',summary:'单日申购上限拟调整为 500 元，可能影响原计划每期 2,000 元的投入安排。',basis:'公告直接涉及你持有的基金份额类别。',impact:'如果下期仍按原金额申购，超出限额的部分可能无法提交。',next:'查看公告生效日及限额口径，再决定是否调整计划提醒或投入安排。'},
  {id:'manager',title:'均衡成长混合 A 基金经理变更',status:'值得了解',time:'9 月 24 日 09:10',fundIds:['f-balanced'],source:'基金临时公告（演示）',summary:'基金管理人披露了基金经理调整；短期净值变化不能直接归因于本次人事变更。',basis:'公告直接对应你持有的这只主动基金。',impact:'需要关注后续投资策略和持仓披露是否出现持续变化。',next:'查看完整公告与后续定期报告，暂不依据单日行情做交易决定。'}
];
const samplePlan={id:'plan-chinext',name:'创业板长期定投计划',fundId:'f-chinext',indexId:'chinext',status:'追踪中',budget:2000,check:'每月 26 日检查',rule:'单期计划投入 2,000 元；基金申购受限时提醒核对，不自动拆单。',version:1,source:'找策略保存的演示计划'};
const rangePerformance={sse:['+1.68%','+8.31%'],szse:['-0.75%','+5.14%'],hs300:['+1.24%','+7.26%'],zz500:['-1.92%','+3.57%'],chinext:['-4.18%','+2.36%'],zz1000:['-2.08%','+4.13%'],dividend:['+2.02%','+9.42%'],bond:['+0.17%','+2.86%'],gold:['+3.20%','+16.51%'],sp500:['+1.91%','+12.38%']};
const key='suvi-market-prototype-v1';
const initial={tab:'mine',view:'mine',marketMode:'trading',indexCategory:'A股大盘',range:'分时',mineFilter:'全部',alertFilter:'全部',indexOrder:['sse','hs300','chinext','zz1000'],favoriteIds:['sse','hs300','chinext','zz1000'],indexSelected:'chinext',fundSelected:null,alertSelected:null,alertsRead:[],compare:[],search:'',chatClosed:false,chatWidth:388,contexts:[{type:'index',id:'chinext'},{type:'fund',id:'f-chinext'}],messages:[{role:'user',text:'今天创业板下跌，和我持有的基金有什么关系？'},{role:'assistant',text:'创业板指在演示行情中下跌 1.42%。你持有的创业板 ETF 联接 C 明确跟踪这一指数，方向可能相关；但它今天的正式净值尚未披露，不能把指数跌幅当成你的持仓收益。\n\n我已把指数与基金放到同一视图，并标出净值时间。下一步可以先看跟踪关系、盘中估算口径，再等正式净值更新。',refs:[{type:'index',id:'chinext'},{type:'fund',id:'f-chinext'}],sources:'演示指数行情 14:35 · 基金净值 9 月 23 日 · 跟踪依据：基金合同（演示）'}],chatInput:'',busy:false,busyLabel:'',chartSelection:null,alertExpand:null,planDraft:null,notice:''};
function clone(value){return JSON.parse(JSON.stringify(value));}
function restore(){try{const saved=JSON.parse(localStorage.getItem(key));return saved&&typeof saved==='object'?Object.assign(clone(initial),saved,{busy:false,busyLabel:'',chatInput:''}):clone(initial);}catch{return clone(initial);}}
let state=restore(),workScroll=0,toastTimer,stageTimer,dragStart=null;
const indexById=id=>indexes.find(row=>row.id===id);
const fundById=id=>funds.find(row=>row.id===id);
const eventById=id=>events.find(row=>row.id===id);
const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function persist(){localStorage.setItem(key,JSON.stringify(Object.assign({},state,{busy:false,busyLabel:'',chatInput:''})));}
function toast(message){const node=document.getElementById('toast');node.textContent=message;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),3600);}
function progress(label,finish){clearTimeout(stageTimer);state.busy=true;state.busyLabel=label;renderChat();stageTimer=setTimeout(()=>{state.busy=false;state.busyLabel='';finish();persist();render();},650);}
function marketStatus(row){if(state.marketMode==='closed')return '休市';if(state.marketMode==='delayed')return '延迟行情';return row.status;}
function marketTime(row){const status=marketStatus(row);return status==='交易中'?'14:35':status==='休市'?'上一交易日收盘':'延迟约 15 分钟';}
function selectedTime(){const selection=state.chartSelection;if(!selection)return state.range+'全区间';const left=Math.min(selection.start,selection.end),right=Math.max(selection.start,selection.end);if(state.range!=='分时')return state.range+'第 '+Math.max(1,Math.round(left))+'%—'+Math.min(100,Math.round(right))+'% 区间';const format=value=>{const tradingMinutes=Math.round(value/100*240),minutes=tradingMinutes<=120?570+tradingMinutes:780+tradingMinutes-120;return String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');};return format(left)+'—'+format(right);}
function stateClass(status){return status==='交易中'?'':status==='休市'?' closed':' delay';}
function rangeChange(row){return state.range==='分时'?row.change:(rangePerformance[row.id]||[row.change,row.change])[state.range==='近一月'?0:1];}
function changeClass(change){return String(change).startsWith('-')?'down':'up';}
function spark(values,kind='small',color){const width=kind==='large'?620:kind==='compare'?620:145,height=kind==='large'?150:kind==='compare'?160:30,min=Math.min(...values)-4,max=Math.max(...values)+4,pts=values.map((n,i)=>(i*width/(values.length-1)).toFixed(1)+','+(height-4-(n-min)/(max-min)*(height-8)).toFixed(1)).join(' ');const stroke=color||'#32876d';return '<svg viewBox="0 0 '+width+' '+height+'" preserveAspectRatio="none" role="img" aria-label="演示走势"><line x1="0" y1="'+(height*.68)+'" x2="'+width+'" y2="'+(height*.68)+'" stroke="#e8ede9"/><line x1="0" y1="'+(height*.32)+'" x2="'+width+'" y2="'+(height*.32)+'" stroke="#e8ede9"/><polyline points="'+pts+'" fill="none" stroke="'+stroke+'" stroke-width="'+(kind==='small'?2:2.4)+'" stroke-linecap="round" stroke-linejoin="round"/></svg>';}
function frame(content){return '<div class="inner"><div class="topline"><div class="breadcrumb">基金工作区 ／ <strong>看行情</strong></div><span class="data-badge"><i></i>交互演示 · 行情和持仓均为示例数据</span></div><nav class="tabs" aria-label="行情页面"><button data-tab="mine" class="'+(state.tab==='mine'?'active':'')+'">我的行情</button><button data-tab="indexes" class="'+(state.tab==='indexes'?'active':'')+'">指数行情</button><button data-tab="alerts" class="'+(state.tab==='alerts'?'active':'')+'">大事提醒 '+events.filter(e=>!state.alertsRead.includes(e.id)).length+'</button><span class="spacer"></span><button class="small-icon" data-action="cycle-market-mode" title="切换交易中、休市与延迟行情演示" aria-label="切换行情状态">◷</button></nav>'+content+'</div>';}
function title(title,description,meta){return '<div class="page-head"><div><h1>'+esc(title)+'</h1><p>'+esc(description)+'</p></div><div class="meta">'+(meta||'')+'</div></div>';}
function indexTile(row){const fav=state.favoriteIds.includes(row.id),status=marketStatus(row);return '<div class="index-tile '+(state.indexSelected===row.id?'selected':'')+'"><div class="tile-top"><strong>'+esc(row.name)+'</strong><button data-action="favorite" data-id="'+row.id+'" title="'+(fav?'取消自选':'加入自选')+'" class="'+(fav?'active':'')+'">'+(fav?'★':'☆')+'</button></div><div class="tile-number"><b>'+esc(row.points)+'</b><em class="'+row.color+'">'+esc(row.change)+'</em></div><div class="tile-bottom">'+spark(row.values,'small',row.color==='up'?'#c65755':'#28866f')+'<small>'+esc(marketTime(row))+'</small></div><button class="text-btn" data-action="open-index" data-id="'+row.id+'" style="padding:3px 0 0">查看指数 →</button></div>';}
function indexStrip(){return '<div class="section-heading"><div><h2>今日市场</h2><p>常用指数一眼可见 · 红涨绿跌</p></div><div class="actions"><span class="market-state'+stateClass(marketStatus(indexes[0]))+'"><i></i>'+esc(marketStatus(indexes[0]))+'</span><button class="text-btn" data-action="edit-order">调整顺序</button></div></div><div class="index-strip">'+state.indexOrder.map(id=>indexTile(indexById(id))).join('')+'</div><div class="index-tools"><span>演示行情时间：'+esc(marketTime(indexes[0]))+' · 不等于基金正式净值</span><button data-tab="indexes">查看全部指数 →</button></div>';}
function filteredFunds(){return funds.filter(row=>state.mineFilter==='有大事'?Boolean(row.event):state.mineFilter==='波动较大'?row.large:state.mineFilter==='待更新净值'?true:true);}
function fundRow(row){const related=row.index?indexById(row.index):null,highlight=state.fundSelected===row.id;return '<tr class="'+(highlight?'highlight':'')+'"><td class="fund-cell"><strong>'+esc(row.name)+'</strong><small>'+esc(row.kind)+' · 示例持仓</small></td><td class="value-cell"><strong>'+esc(row.nav)+'</strong><small>'+esc(row.navDate)+' 正式净值</small></td><td class="'+(row.month.startsWith('-')?'down':'up')+'"><strong>'+esc(row.month)+'</strong><small style="display:block;color:#97a39a;font-size:8px">近一月</small></td><td>'+(related?'<span class="fund-pill">跟踪 '+esc(related.name)+'</span>':'<span class="fund-pill">无固定跟踪指数</span>')+'</td><td>'+(row.event?'<span class="event-pill">'+esc(row.event)+'</span>':'<span class="event-pill quiet">暂无</span>')+'</td><td><button class="row-action" data-action="open-fund" data-id="'+row.id+'" aria-label="查看'+esc(row.name)+'">→</button></td></tr>';}
function alertTeasers(){return '<div class="market-alerts">'+events.map(event=>'<button data-action="open-alert" data-id="'+event.id+'"><span class="alert-status '+(event.status==='需要处理'?'action':'')+'">'+esc(event.status)+'</span><strong>'+esc(event.title)+'</strong><small>'+esc(event.time)+' · 查看依据 →</small></button>').join('')+'</div>';}
function myMarkets(){const visible=filteredFunds(),filters=['全部','有大事','波动较大','待更新净值'];return frame(title('我的行情','先看大盘，再看我的基金和需要关注的事。','<span class="market-state'+stateClass(marketStatus(indexes[0]))+'"><i></i>'+esc(marketStatus(indexes[0]))+'</span>')+indexStrip()+'<div class="summary-grid"><div class="summary"><small>持仓基金</small><strong>4</strong><span>示例账户</span></div><div class="summary"><small>今日正式净值已披露</small><strong>0</strong><span>前一日净值已可查</span></div><div class="summary"><small>今日正式净值待披露</small><strong>4</strong><span>不可用指数代替</span></div><div class="summary alert"><small>持仓相关大事</small><strong>2</strong><span>其中 1 项需核对计划</span></div></div>'+alertTeasers()+'<div class="section-heading"><div><h2>我的持仓基金</h2><p>正式净值、盘中估算和实时指数采用不同标识</p></div><div class="actions"><button class="text-btn" data-tab="alerts">查看大事提醒 →</button></div></div><div class="section-card"><div class="filterbar">'+filters.map(name=>'<button data-filter="'+name+'" class="'+(state.mineFilter===name?'active':'')+'">'+name+'</button>').join('')+'<span class="spacer"></span><small>'+visible.length+' 只基金</small></div><table class="holdings-table"><thead><tr><th>持仓基金</th><th>最新净值</th><th>阶段表现</th><th>相关指数</th><th>事件</th><th></th></tr></thead><tbody>'+visible.map(fundRow).join('')+'</tbody></table><div class="data-foot">今日指数为 14:35 演示行情；基金净值为 9 月 23 日的正式披露值。盘中估算只用于参考，不能当作最终净值或账户收益。</div></div><div class="signal-banner"><b>计划检查条件已触发</b><span>创业板定投计划关联基金的申购限额发生变化；需要核对下期投入安排。</span><button data-action="open-plan-trigger">查看依据 →</button></div>');}
function categoryRows(){if(state.indexCategory==='我的自选')return indexes.filter(row=>state.favoriteIds.includes(row.id));if(state.indexCategory==='A股大盘')return indexes.filter(row=>['sse','szse','hs300','zz500','chinext'].includes(row.id));if(state.indexCategory==='风格与行业')return indexes.filter(row=>['zz1000','dividend','chinext','zz500'].includes(row.id));if(state.indexCategory==='债市与商品')return indexes.filter(row=>['bond','gold'].includes(row.id));return indexes.filter(row=>row.category==='海外');}
function indexRow(row){const selected=state.compare.includes(row.id),fav=state.favoriteIds.includes(row.id);return '<div class="index-row"><div><strong>'+esc(row.name)+'</strong><small>'+esc(row.category)+' · '+esc(marketTime(row))+'</small></div><div class="quote">'+esc(row.points)+'</div><div class="change '+row.color+'">'+esc(row.change)+'</div><div><small>'+esc(row.amount)+'</small></div><div><span class="market-state'+stateClass(marketStatus(row))+'"><i></i>'+esc(marketStatus(row))+'</span></div><div>'+spark(row.values,'small',row.color==='up'?'#c65755':'#28866f')+'</div><div><button class="mini-add '+(selected?'active':'')+'" data-action="compare-index" data-id="'+row.id+'" title="'+(selected?'移出对比':'加入对比')+'">'+(selected?'✓':'＋')+'</button></div><button class="row-button" data-action="open-index" data-id="'+row.id+'" style="grid-column:1/-1">查看指数、相关持仓与今天发生的事 →</button></div>';}
function compareTray(){if(!state.compare.length)return '';return '<div class="compare-tray"><strong>对比 '+state.compare.length+'/3</strong>'+state.compare.map(id=>'<span>'+esc(indexById(id).name)+'</span>').join('')+'<button class="primary" data-action="show-comparison" '+(state.compare.length<2?'disabled':'')+'>查看对比 →</button></div>';}
function indexWorkspace(){const categories=['A股大盘','风格与行业','债市与商品','海外市场','我的自选'],rows=categoryRows().filter(row=>!state.search||row.name.includes(state.search));return frame(title('指数行情','看清市场变化，以及它和你的持仓有何关系。','<span class="market-state'+stateClass(marketStatus(indexes[0]))+'"><i></i>'+esc(marketStatus(indexes[0]))+'</span>')+'<div class="category-tabs">'+categories.map(name=>'<button data-category="'+name+'" class="'+(state.indexCategory===name?'active':'')+'">'+name+'</button>').join('')+'</div><div class="section-heading"><div><h2>'+esc(state.indexCategory)+'</h2><p>点开指数可看走势、证据和持仓对照</p></div><div class="actions"><label class="search-box">⌕ <input id="index-search" value="'+esc(state.search)+'" placeholder="搜索指数" aria-label="搜索指数"></label></div></div><div class="index-list">'+(rows.map(indexRow).join('')||'<div class="panel">没有找到指数</div>')+'</div><div class="data-foot" style="margin-top:10px;background:#fff;border:1px solid #e0e7e1;border-radius:7px">不同市场交易时段和数据延迟可能不同；休市或延迟状态下不把涨跌幅与 A 股盘中行情直接并列解读。</div>'+compareTray());}
function chartBlock(row){const c=state.chartSelection;return '<div class="range-tabs">'+['分时','近一月','近一年'].map(name=>'<button data-range="'+name+'" class="'+(state.range===name?'active':'')+'">'+name+'</button>').join('')+'</div><div class="chart-wrap" id="selectable-chart" data-id="'+row.id+'">'+spark(row.values,'large',row.color==='up'?'#c65755':'#28866f')+(c?'<div class="chart-select" style="left:'+Math.min(c.start,c.end)+'%;width:'+Math.abs(c.end-c.start)+'%"></div>':'')+'</div><div class="chart-axis"><span>'+(state.range==='分时'?'09:30':'区间起点')+'</span><span>'+(state.range==='分时'?'11:30':'区间中点')+'</span><span>'+(state.range==='分时'?'15:00':'区间终点')+'</span></div><div class="chart-hint"><span>'+(c?'已选区间：'+selectedTime():'在走势图上拖动选择一段区间')+'</span><button class="text-btn" data-action="ask-chart" data-id="'+row.id+'">问苏维这段变化 ↗</button></div>';}
function relatedFunds(row){const related=funds.filter(fund=>fund.index===row.id);return related.length?related.map(fund=>'<div class="related-card"><strong>'+esc(fund.name)+'</strong><small>依据：基金合同约定跟踪 '+esc(row.name)+'</small><span class="tag">正式净值 '+esc(fund.nav)+' · '+esc(fund.navDate)+'</span><div class="note">今日指数行情已更新，基金净值待披露。</div><button class="text-btn" data-action="open-fund" data-id="'+fund.id+'">查看基金 →</button></div>').join(''):'<div class="related-card"><strong>没有直接跟踪关系的持仓基金</strong><small>主动基金与债券基金不按本指数涨跌推断今日收益。</small></div>';}
function indexDetail(){const row=indexById(state.indexSelected)||indexes[0],status=marketStatus(row),fact='演示行情显示 '+row.name+' 为 '+row.points+' 点，涨跌幅 '+row.change+'，'+row.amount+'。',possible='目前只有指数行情，无法凭指数走势确认全部涨跌原因；需结合成分、成交与可核验新闻继续分析。';return frame('<div class="backline"><button data-action="back-indexes">← 返回指数行情</button><span>／ '+esc(row.name)+'</span></div>'+title(row.name,row.note,'<span class="market-state'+stateClass(status)+'"><i></i>'+esc(status)+'</span>')+'<div class="detail-grid"><section class="panel"><div class="big-quote"><strong>'+esc(row.points)+'</strong><span class="'+row.color+'">'+esc(row.change)+'</span><small style="color:#91a094;font-size:9px">'+esc(marketTime(row))+'</small></div>'+chartBlock(row)+'<div class="detail-stats"><div><small>'+(state.range==='分时'?'今日涨跌幅':state.range+'表现')+'</small><strong class="'+changeClass(rangeChange(row))+'">'+esc(rangeChange(row))+'</strong></div><div><small>成交或指标</small><strong style="font-size:10px">'+esc(row.amount)+'</strong></div><div><small>数据状态</small><strong style="font-size:10px">'+esc(status)+'</strong></div></div><div class="data-foot">走势图、点位与指标均为演示数据；正式产品须标注行情提供方、采集时间及延迟。</div></section><section class="panel"><h2>今天发生了什么</h2><div class="evidence"><div><strong>已确认的行情事实</strong><p>'+esc(fact)+'</p></div><div><strong>仍需核实的可能因素</strong><p>'+esc(possible)+'</p></div></div><div class="section-heading"><div><h2>可继续查看</h2></div></div><button class="secondary" data-action="favorite" data-id="'+row.id+'">'+(state.favoriteIds.includes(row.id)?'移出自选':'加入自选')+'</button> <button class="secondary" data-action="see-related" data-id="'+row.id+'">查看相关基金</button><p>数据时间：'+esc(marketTime(row))+'。指数变化不能直接当作基金净值。</p></section></div><div class="crosswalk" id="holdings-crosswalk"><section class="panel"><h2>大盘与我的持仓</h2><p>左侧为 '+esc(row.name)+' 的演示走势。右侧仅列出有明确跟踪关系的持仓基金。</p>'+spark(row.values,'large',row.color==='up'?'#c65755':'#28866f')+'<div class="data-foot">指数 '+esc(row.change)+' · '+esc(marketTime(row))+'；基金今日正式净值尚未披露。</div></section><section class="panel"><h2>相关持仓基金</h2><div class="related-list">'+relatedFunds(row)+'</div><button class="text-btn" data-action="ask-difference" data-id="'+row.id+'">解释跟踪误差与时差 ↗</button></section></div><div class="signal-banner"><b>计划关联</b><span>'+esc(samplePlan.name)+' 关注 '+esc(row.name)+'；当前提醒来自基金申购限额变更，不是涨跌触发的买卖信号。</span><button data-action="open-plan-trigger">查看计划依据 →</button></div>'+compareTray());}
function fundDetail(){const fund=fundById(state.fundSelected)||funds[0],related=fund.index?indexById(fund.index):null,alert=fund.eventId?eventById(fund.eventId):null;return frame('<div class="backline"><button data-action="back-mine">← 返回我的行情</button><span>／ '+esc(fund.name)+'</span></div>'+title(fund.name,fund.kind+' · 示例持仓 · 最新正式净值 '+fund.navDate,'<span class="data-badge"><i></i>今日正式净值待披露</span>')+'<div class="detail-grid"><section class="panel"><h2>净值走势</h2><div class="big-quote"><strong>'+esc(fund.nav)+'</strong><small style="color:#879789;font-size:9px">'+esc(fund.navDate)+' 正式净值</small></div>'+spark(fund.values,'large','#3e8a71')+'<div class="detail-stats"><div><small>近一月表现</small><strong class="'+(fund.month.startsWith('-')?'down':'up')+'">'+esc(fund.month)+'</strong></div><div><small>盘中参考</small><strong style="font-size:10px">'+esc(fund.estimate)+'</strong></div><div><small>今日正式净值</small><strong style="font-size:10px">待披露</strong></div></div><div class="data-foot">盘中估算可能使用已披露持仓或指数映射，与实际净值可能存在偏差；不代表用户今日收益。</div></section><section class="panel"><h2>相关市场变化</h2>'+(related?'<div class="related-card"><strong>明确跟踪 '+esc(related.name)+'</strong><small>'+esc(fund.relation)+'</small><div class="note">指数 '+esc(related.change)+' · '+esc(marketTime(related))+'；今日基金净值待披露。</div><button class="text-btn" data-action="open-index" data-id="'+related.id+'">查看指数 →</button></div>':'<div class="related-card"><strong>无单一指数直接对应</strong><small>'+esc(fund.relation)+'</small></div>')+'<div class="section-heading"><h2>近期公告</h2></div>'+(alert?'<div class="related-card"><strong>'+esc(alert.title)+'</strong><small>'+esc(alert.time)+' · '+esc(alert.source)+'</small><button class="text-btn" data-action="open-alert" data-id="'+alert.id+'">查看提醒 →</button></div>':'<p>当前演示场景没有与该基金相关的新公告。</p>')+'</section></div>');}
function indexComparison(){const selected=state.compare.length>=2?state.compare:['sse','chinext'],rows=selected.map(indexById).filter(Boolean),scale=Math.min(35,60/Math.max(1,...rows.map(row=>Math.abs(Number.parseFloat(rangeChange(row))))));return frame('<div class="backline"><button data-action="back-indexes">← 返回指数行情</button><span>／ 指数对比</span></div>'+title('指数对比','同一演示时间段、同一涨跌幅口径下看大盘与风格差异。','最多 3 个指数')+'<div class="range-tabs">'+['分时','近一月','近一年'].map(name=>'<button data-range="'+name+'" class="'+(state.range===name?'active':'')+'">'+name+'</button>').join('')+'</div><div class="compare-lines"><svg viewBox="0 0 620 160" preserveAspectRatio="none" role="img" aria-label="指数对比演示曲线">'+rows.map((row,j)=>{const target=Number.parseFloat(rangeChange(row)),start=row.values[0],delta=row.values.at(-1)-start,pts=row.values.map((v,i)=>(i*620/(row.values.length-1)).toFixed(1)+','+Math.max(8,Math.min(152,80-(delta?(v-start)/delta*target:0)*scale)).toFixed(1)).join(' ');return '<polyline points="'+pts+'" fill="none" stroke="'+['#bb5653','#357c94','#c39b51'][j]+'" stroke-width="2.4"/>';}).join('')+'</svg></div><div class="data-foot">演示曲线共用零涨跌基线与纵轴尺度，仅用于展示交互；正式产品必须统一交易日、时段和数据来源。</div><div class="section-card" style="margin-top:13px"><table class="compare-table"><thead><tr><th>项目</th>'+rows.map(row=>'<th>'+esc(row.name)+'</th>').join('')+'</tr></thead><tbody><tr><td>行情状态</td>'+rows.map(row=>'<td>'+esc(marketStatus(row))+'</td>').join('')+'</tr><tr><td>'+esc(state.range)+'演示涨跌幅</td>'+rows.map(row=>'<td><strong class="'+changeClass(rangeChange(row))+'">'+esc(rangeChange(row))+'</strong></td>').join('')+'</tr><tr><td>成交或指标</td>'+rows.map(row=>'<td>'+esc(row.amount)+'</td>').join('')+'</tr><tr><td>我的相关基金</td>'+rows.map(row=>'<td>'+esc(funds.filter(f=>f.index===row.id).map(f=>f.name).join('、')||'无明确跟踪关系')+'</td>').join('')+'</tr></tbody></table></div><div class="section-heading"><p>同一市场尚可比较；休市或延迟行情会标注状态，不与盘中实时值直接比较。</p><button class="text-btn" data-action="ask-comparison">问苏维这些差异 →</button></div>');}
function alertStatus(event){return state.alertsRead.includes(event.id)?'已读':event.status;}
function alertCard(event){const expanded=state.alertExpand===event.id,status=alertStatus(event),fundNames=event.fundIds.map(id=>fundById(id)?.name||id).join('、');return '<article class="alert-card '+(expanded?'selected':'')+'"><div class="alert-top"><span class="alert-status '+(status==='需要处理'?'action':status==='已读'?'read':'')+'">'+esc(status)+'</span><strong>'+esc(event.title)+'</strong><time>'+esc(event.time)+'</time></div><p>'+esc(event.summary)+'</p><div class="alert-meta"><span>关联持仓：'+esc(fundNames)+'</span><span>来源：'+esc(event.source)+'</span></div>'+(expanded?'<div class="alert-more"><dl><dt>发生了什么</dt><dd>'+esc(event.summary)+'</dd><dt>关联依据</dt><dd>'+esc(event.basis)+'</dd><dt>可能影响</dt><dd>'+esc(event.impact)+'</dd><dt>下一步</dt><dd>'+esc(event.next)+'</dd></dl><div class="alert-actions"><button class="secondary" data-action="ask-alert" data-id="'+event.id+'">问苏维这条提醒</button><button class="secondary" data-action="mark-read" data-id="'+event.id+'">标为已读</button>'+(event.id==='limit'?'<button class="primary" data-action="open-plan-trigger">核对关联计划</button>':'')+'</div></div>':'<button class="text-btn" data-action="open-alert" data-id="'+event.id+'">展开查看依据与影响 →</button>')+'</article>';}
function alertsWorkspace(){const filters=['全部','需要处理','值得了解','已读'],rows=events.filter(row=>state.alertFilter==='全部'||alertStatus(row)===state.alertFilter);return frame(title('持仓大事提醒','只呈现与持仓有明确关联的变化，并说明下一步。','<span class="data-badge"><i></i>公告来源为演示</span>')+'<div class="alert-tools">'+filters.map(name=>'<button data-alert-filter="'+name+'" class="'+(state.alertFilter===name?'active':'')+'">'+name+'</button>').join('')+'</div><div class="alerts-list">'+(rows.map(alertCard).join('')||'<div class="panel">当前筛选下没有提醒</div>')+'</div><div class="data-foot" style="margin-top:12px">同一事项影响多只持仓时应合并呈现。依据来自定期报告重仓股时，必须标注报告期与披露滞后性；不能暗示基金当前仍持有。</div>');}
function planAdjustment(){const plan=state.plan||samplePlan;return frame('<div class="backline"><button data-action="back-alerts">← 返回大事提醒</button><span>／ 计划调整草稿</span></div>'+title('计划调整草稿','申购限额变化触发了计划里的检查条件；原计划不会自动修改。','规则版本 v'+plan.version)+'<div class="signal-banner" style="margin:0 0 14px"><b>触发依据</b><span>'+esc(events[0].title)+' · '+esc(events[0].source)+'</span></div><div class="detail-grid"><section class="panel"><h2>调整前</h2><p><strong>'+esc(plan.name)+'</strong> · '+esc(plan.status)+'</p><div class="detail-stats"><div><small>单期预算</small><strong>2,000 元</strong></div><div><small>检查时间</small><strong>'+esc(plan.check)+'</strong></div><div><small>版本</small><strong>v'+plan.version+'</strong></div></div><p>'+esc(plan.rule)+'</p></section><section class="panel"><h2>建议调整后</h2><p>提前核对申购限制，由你决定剩余预算去向。</p><div class="detail-stats"><div><small>月度预算</small><strong>仍为 2,000 元</strong></div><div><small>检查时间</small><strong>每月 24 日</strong></div><div><small>单日申购</small><strong>上限 500 元</strong></div></div><p>剩余预算不自动转购其他基金，也不自动拆成多笔；需你确认安排。</p></section></div><div class="signal-banner"><b>仍需确认</b><span>公告生效日期、限购是否适用于你的份额类别、剩余预算的使用方式。</span></div><div class="section-heading"><button class="secondary" data-action="back-alerts">暂不修改</button><button class="primary" data-action="confirm-plan-adjustment">确认更新提醒规则</button></div><p class="data-foot">确认仅更新演示计划的提醒规则与版本，不会发起申购、撤单或其他交易。</p>');}
function renderWorkspace(){const node=document.getElementById('workspace');node.innerHTML=state.view==='indexDetail'?indexDetail():state.view==='fundDetail'?fundDetail():state.view==='comparison'?indexComparison():state.view==='alerts'?alertsWorkspace():state.view==='planAdjustment'?planAdjustment():state.view==='indexes'?indexWorkspace():myMarkets();if(state.showOrder&&state.view==='mine'){const tools=node.querySelector('.index-tools');tools.insertAdjacentHTML('afterend','<div class="order-editor">'+state.indexOrder.map((id,i)=>'<div><strong>'+esc(indexById(id).name)+'</strong><button data-action="move-index" data-id="'+id+'" data-direction="up" '+(i===0?'disabled':'')+'>上移</button><button data-action="move-index" data-id="'+id+'" data-direction="down" '+(i===state.indexOrder.length-1?'disabled':'')+'>下移</button></div>').join('')+'<button class="text-btn" data-action="edit-order">完成调整</button></div>');}}
function refButton(ref){const item=ref.type==='index'?indexById(ref.id):ref.type==='fund'?fundById(ref.id):ref.type==='alert'?eventById(ref.id):null;if(!item)return '';return '<button data-action="open-reference" data-type="'+ref.type+'" data-id="'+ref.id+'"><span>'+esc(item.name||item.title)+'</span><b>查看证据 →</b></button>';}
function messageView(message){return '<div class="chat-message '+(message.role==='user'?'user':'assistant')+'"><div class="who">'+(message.role==='user'?'你':'✦ 苏维')+'</div><div class="bubble">'+esc(message.text)+'</div>'+(message.refs?.length?'<div class="refs">'+message.refs.map(refButton).join('')+'</div>':'')+(message.sources?'<div class="sources">依据：'+esc(message.sources)+'</div>':'')+'</div>';}
function contextLabel(context){const item=context.type==='index'?indexById(context.id):context.type==='fund'?fundById(context.id):context.type==='alert'?eventById(context.id):context.type==='plan'?state.plan||samplePlan:null;return item?.name||item?.title||'关联计划';}
function renderChat(){const node=document.getElementById('assistant');if(state.chatClosed){node.innerHTML='<div class="assistant-closed"><button data-action="open-chat" title="展开苏维">✦</button><p>正在讨论行情与持仓</p><small>点击恢复</small></div>';return;}const contexts=state.contexts.map((context,i)=>'<span class="context-chip">'+esc(contextLabel(context))+' <button data-action="remove-context" data-index="'+i+'" title="移出上下文">×</button></span>').join('');node.innerHTML='<div class="assistant-head"><div><strong>问问我的行情</strong><small>交互演示 · 围绕当前页面讨论</small></div><button data-action="close-chat">收起</button></div><div class="context"><span>当前讨论：</span>'+(contexts||'<span>整个行情工作区</span>')+'</div><div class="chat-log" id="chat-log">'+(state.messages.length?state.messages.map(messageView).join(''):'<div class="chat-message"><div class="who">✦ 苏维</div><div class="bubble">你想先看今天的大盘、自己的基金，还是一条持仓提醒？</div></div>')+(state.busy?'<div class="chat-loading"><i></i>'+esc(state.busyLabel)+' <button class="text-btn" data-action="cancel-stage">取消</button></div>':'')+'<div class="quick-prompts"><button data-prompt="看看今天的大盘">看看今天的大盘</button><button data-prompt="创业板跌了，影响我的哪些基金？">创业板跌了，影响我的哪些基金？</button><button data-prompt="这条提醒需要处理吗？">这条提醒需要处理吗？</button></div></div><div class="composer"><textarea id="chat-input" placeholder="问大盘、基金或这条提醒…">'+esc(state.chatInput)+'</textarea><div class="composer-row"><small>回车换行 · 按住控制键或命令键后回车发送</small><button data-action="send-chat" '+(state.busy?'disabled':'')+'>发送 ↑</button></div></div>';const log=document.getElementById('chat-log');log.scrollTop=log.scrollHeight;}
function render(){document.documentElement.style.setProperty('--chat',state.chatWidth+'px');document.body.classList.toggle('chat-closed',state.chatClosed);renderWorkspace();renderChat();}
function currentContext(type,id){state.contexts=[{type,id}];}
function addMessage(text,refs,sources){state.messages.push({role:'assistant',text,refs:refs||[],sources:sources||''});}
function ask(text){const message=String(text||'').trim();if(!message||state.busy)return;state.messages.push({role:'user',text:message});state.chatInput='';let response='',refs=[],sources='',label='正在核对行情与持仓';
  if(/卖|赎回|清仓/.test(message)){response='单日指数下跌不足以直接决定是否卖出。先核对你的资金使用时间、可接受的亏损和“'+(state.plan||samplePlan).name+'”的规则；今天的基金正式净值尚未披露，不能按指数跌幅计算你的实际损益。你可以先查看计划是否有明确检查条件。';refs=[{type:'index',id:'chinext'},{type:'fund',id:'f-chinext'}];sources='演示指数行情、9 月 23 日正式净值、演示计划规则';label='正在核对计划规则与净值时间';}
  else if(/提醒|限购|需要处理/.test(message)){state.tab='alerts';state.view='alerts';state.alertExpand='limit';state.alertSelected='limit';currentContext('alert','limit');response='这条提醒需要核对，因为公告示例显示单日申购上限拟改为 500 元，而关联计划的单期预算为 2,000 元。请先核实公告生效日及份额类别，再决定是否调整计划；苏维不会自动拆单或买入。';refs=[{type:'alert',id:'limit'},{type:'fund',id:'f-chinext'}];sources='基金临时公告（演示） · 计划规则 v'+(state.plan||samplePlan).version;label='正在核对公告与计划条件';}
  else if(/调整计划|修改计划/.test(message)){state.view='planAdjustment';state.tab='alerts';state.contexts=[{type:'plan',id:'plan-chinext'},{type:'alert',id:'limit'}];response='我已生成提醒规则的调整草稿：把限购检查提前到每月 24 日，月度预算仍为 2,000 元。剩余预算如何安排仍需你确认；原计划不会在你确认前变化。';refs=[{type:'alert',id:'limit'}];sources='演示公告 · 演示计划规则';label='正在生成调整草稿';}
  else if(/跟踪误差|时差|估算/.test(message)){const row=indexById(state.indexSelected)||indexes[4];response='指数是盘中行情，基金正式净值通常在交易日结束后披露。即使基金明确跟踪 '+row.name+'，费用、现金仓位、申赎和估值时间也可能造成差异。盘中估算只是参考，今天的指数涨跌不能直接算成你的账户收益。';refs=[{type:'index',id:row.id},{type:'fund',id:'f-chinext'}];sources='指数演示行情 14:35 · 基金合同关系（演示） · 正式净值 9 月 23 日';label='正在核对指数与基金口径';}
  else if(/这段|区间|上涨.*发生/.test(message)&&state.view==='indexDetail'){const row=indexById(state.indexSelected)||indexes[0];response='你选中了'+selectedTime()+'。已确认的事实是 '+row.name+' 当前演示涨跌幅 '+row.change+'、'+row.amount+'。仅凭这张走势图无法确认上涨或下跌的主因；需要进一步核对成分表现、成交和同期事件。';refs=[{type:'index',id:row.id}];sources='选中演示图表区间 · 演示指数行情';label='正在核对选中区间的数据';}
  else if(/对比|这几个指数|表现差异/.test(message)){const selected=state.compare.length>=2?state.compare:['sse','chinext'],rows=selected.map(indexById).filter(Boolean),related=funds.filter(fund=>selected.includes(fund.index));state.tab='indexes';state.view='comparison';state.contexts=selected.map(id=>({type:'index',id}));response='这组演示指数分别为 '+rows.map(row=>row.name+' '+row.change).join('、')+'，反映出市场风格差异。'+(related.length?'你持有的'+related.map(fund=>fund.name).join('、')+'有明确跟踪关系；':'当前持仓与所选指数没有明确跟踪关系；')+'主动基金不能按单一指数解释。今日基金正式净值仍待披露，先看各基金的跟踪依据和净值日期。';refs=rows.map(row=>({type:'index',id:row.id}));sources='演示指数行情 14:35 · 基金合同关系（演示） · 正式净值 9 月 23 日';label='正在对齐指数时间与持仓关系';}
  else if(/创业板/.test(message)){state.tab='indexes';state.view='indexDetail';state.indexSelected='chinext';state.fundSelected='f-chinext';state.contexts=[{type:'index',id:'chinext'},{type:'fund',id:'f-chinext'}];response='创业板指在演示行情中下跌 1.42%。你持有的创业板 ETF 联接 C 根据基金合同跟踪该指数，因此方向可能相关。它今天的正式净值尚未披露；盘中估算 -1.18% 也不是你的实际收益。主动基金没有单一指数跟踪关系，不能按创业板跌幅推断。';refs=[{type:'index',id:'chinext'},{type:'fund',id:'f-chinext'}];sources='演示指数行情 14:35 · 基金净值 9 月 23 日 · 跟踪依据：基金合同（演示）';label='正在核对基金跟踪关系';}
  else if(/大盘|今天行情|市场/.test(message)){state.tab='mine';state.view='mine';state.contexts=[{type:'index',id:'sse'},{type:'index',id:'chinext'}];response='演示行情中，上证指数上涨 0.36%，沪深300上涨 0.18%，创业板指下跌 1.42%。大盘与成长风格出现分化。指数时间为 14:35；你的基金今天正式净值仍待披露。下一步可查看创业板与相关持仓的明确跟踪关系。';refs=[{type:'index',id:'sse'},{type:'index',id:'chinext'}];sources='演示指数行情 14:35 · 基金净值状态 9 月 23 日';label='正在汇总主要指数';}
  else{response='我已看到你当前打开的行情对象。为了给出可核对的解释，请告诉我是想看指数变化、某只持仓基金，还是一条具体提醒；我会先给已确认的数据，再说明仍待核实的因素。';label='正在整理当前上下文';}
  progress(label,()=>addMessage(response,refs,sources));persist();render();}

document.addEventListener('click',event=>{const target=event.target.closest('[data-action],[data-tab],[data-filter],[data-category],[data-alert-filter],[data-range],[data-prompt]');if(!target)return;const action=target.dataset.action,id=target.dataset.id;if(target.dataset.prompt){ask(target.dataset.prompt);return;}if(target.dataset.tab){state.tab=target.dataset.tab;state.view=target.dataset.tab;state.alertExpand=null;persist();render();return;}if(target.dataset.filter){state.mineFilter=target.dataset.filter;persist();renderWorkspace();return;}if(target.dataset.category){state.indexCategory=target.dataset.category;state.search='';persist();renderWorkspace();return;}if(target.dataset.alertFilter){state.alertFilter=target.dataset.alertFilter;persist();renderWorkspace();return;}if(target.dataset.range){state.range=target.dataset.range;state.chartSelection=null;persist();renderWorkspace();return;}
  if(action==='open-index'){state.indexSelected=id;state.tab='indexes';state.view='indexDetail';state.chartSelection=null;currentContext('index',id);persist();render();return;}
  if(action==='open-fund'){state.fundSelected=id;state.tab='mine';state.view='fundDetail';currentContext('fund',id);persist();render();return;}
  if(action==='open-alert'){state.alertExpand=id;state.alertSelected=id;state.tab='alerts';state.view='alerts';currentContext('alert',id);persist();render();return;}
  if(action==='open-reference'){const type=target.dataset.type;if(type==='index'){state.indexSelected=id;state.view='indexDetail';state.tab='indexes';}else if(type==='fund'){state.fundSelected=id;state.view='fundDetail';state.tab='mine';}else if(type==='alert'){state.alertExpand=id;state.view='alerts';state.tab='alerts';}currentContext(type,id);persist();render();return;}
  if(action==='back-indexes'){state.tab='indexes';state.view='indexes';state.chartSelection=null;persist();render();return;}
  if(action==='back-mine'){state.tab='mine';state.view='mine';persist();render();return;}
  if(action==='back-alerts'){state.tab='alerts';state.view='alerts';persist();render();return;}
  if(action==='favorite'){state.favoriteIds=state.favoriteIds.includes(id)?state.favoriteIds.filter(value=>value!==id):state.favoriteIds.concat(id);if(state.favoriteIds.includes(id)&&!state.indexOrder.includes(id)&&state.indexOrder.length<4)state.indexOrder.push(id);if(!state.favoriteIds.includes(id))state.indexOrder=state.indexOrder.filter(value=>value!==id);persist();renderWorkspace();toast(state.favoriteIds.includes(id)?'已加入指数自选':'已移出指数自选');return;}
  if(action==='edit-order'){state.showOrder=!state.showOrder;renderWorkspace();return;}
  if(action==='move-index'){const position=state.indexOrder.indexOf(id),next=position+(target.dataset.direction==='up'?-1:1);if(next>=0&&next<state.indexOrder.length){[state.indexOrder[position],state.indexOrder[next]]=[state.indexOrder[next],state.indexOrder[position]];persist();renderWorkspace();}return;}
  if(action==='compare-index'){state.compare=state.compare.includes(id)?state.compare.filter(value=>value!==id):state.compare.length<3?state.compare.concat(id):state.compare;if(!state.compare.includes(id)&&state.compare.length===3)toast('最多对比 3 个指数');persist();renderWorkspace();return;}
  if(action==='show-comparison'){state.view='comparison';state.tab='indexes';state.contexts=state.compare.map(value=>({type:'index',id:value}));persist();render();return;}
  if(action==='cycle-market-mode'){state.marketMode=state.marketMode==='trading'?'closed':state.marketMode==='closed'?'delayed':'trading';persist();render();toast('已切换为'+(state.marketMode==='trading'?'交易中':state.marketMode==='closed'?'休市':'延迟行情')+'演示');return;}
  if(action==='see-related'){document.getElementById('holdings-crosswalk')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
  if(action==='mark-read'){if(!state.alertsRead.includes(id))state.alertsRead.push(id);persist();render();toast('已标为已读');return;}
  if(action==='open-plan-trigger'){state.tab='alerts';state.view='planAdjustment';state.contexts=[{type:'plan',id:'plan-chinext'},{type:'alert',id:'limit'}];persist();render();return;}
  if(action==='confirm-plan-adjustment'){state.plan=Object.assign({},state.plan||samplePlan,{version:(state.plan?.version||samplePlan.version)+1,check:'每月 24 日提前核对限购',rule:'月度预算 2,000 元；申购限额需提前核对，剩余预算由你确认，不自动拆单。'});state.view='alerts';state.tab='alerts';state.alertExpand='limit';persist();render();toast('提醒规则已更新，原预算保留；未执行交易');return;}
  if(action==='ask-alert'){ask('这条提醒需要处理吗？');return;}
  if(action==='ask-difference'){ask('指数和基金为什么会有跟踪误差、净值时差？');return;}
  if(action==='ask-chart'){ask('这段变化主要发生了什么？');return;}
  if(action==='ask-comparison'){ask('这几个指数的表现差异和我的持仓有什么关系？');return;}
  if(action==='close-chat'){state.chatClosed=true;persist();render();return;}
  if(action==='open-chat'){state.chatClosed=false;persist();render();return;}
  if(action==='remove-context'){state.contexts.splice(Number(target.dataset.index),1);persist();renderChat();return;}
  if(action==='cancel-stage'){clearTimeout(stageTimer);state.busy=false;state.busyLabel='';renderChat();toast('已取消，之前的内容保留');return;}
  if(action==='send-chat'){ask(document.getElementById('chat-input')?.value);return;}
});
document.addEventListener('input',event=>{if(event.target.id==='chat-input')state.chatInput=event.target.value;if(event.target.id==='index-search'){state.search=event.target.value;const start=event.target.selectionStart;renderWorkspace();const input=document.getElementById('index-search');input?.focus();input?.setSelectionRange(start,start);}});
document.addEventListener('keydown',event=>{if(event.target.id==='chat-input'&&event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();ask(event.target.value);}if(event.target.id==='resizer'&&(event.key==='ArrowLeft'||event.key==='ArrowRight')){state.chatWidth=Math.max(310,Math.min(560,state.chatWidth+(event.key==='ArrowLeft'?20:-20)));document.documentElement.style.setProperty('--chat',state.chatWidth+'px');persist();}});
document.addEventListener('pointerdown',event=>{const chart=event.target.closest('#selectable-chart');if(!chart)return;const rect=chart.getBoundingClientRect();dragStart={left:rect.left,width:rect.width,start:Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100))};});
document.addEventListener('pointerup',event=>{if(!dragStart)return;const end=Math.max(0,Math.min(100,(event.clientX-dragStart.left)/dragStart.width*100));state.chartSelection={start:dragStart.start,end:Math.abs(end-dragStart.start)<3?Math.min(100,dragStart.start+10):end};dragStart=null;persist();renderWorkspace();toast('已选中图表区间，可直接问苏维');});
const resizer=document.getElementById('resizer');let resizing=false;resizer.addEventListener('pointerdown',event=>{resizing=true;resizer.setPointerCapture(event.pointerId);});resizer.addEventListener('pointermove',event=>{if(!resizing)return;state.chatWidth=Math.max(310,Math.min(560,innerWidth-event.clientX));document.documentElement.style.setProperty('--chat',state.chatWidth+'px');});resizer.addEventListener('pointerup',()=>{resizing=false;persist();});
document.getElementById('new-question').addEventListener('click',()=>{state.messages=[];state.contexts=[];state.chatInput='';state.chatClosed=false;state.view='mine';state.tab='mine';persist();render();toast('已开始新的行情讨论');});
render();
